apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-website
  template:
    metadata:
      labels:
        app: simple-website
    spec:
      containers:
      - name: website-container
        image: simple-website:v1
        ports:
        - containerPort: 80
